### ISSUE TITLE
Naming functions

### ISSUE THREAD

**Issue by joostf** [heralt/web-app-from-scratch-1920#13]
https://github.com/heralt/web-app-from-scratch-1920/blob/c7ad3329c434d0a2649948606bcd0030d5c7a2fd/assets/script.js#L27-L35

Maybe call the function cleanData instead of getWantedData?
And are you sure you want to call display() from within this function? Or maybe from within the then?

**Comment by heralt** [comment]
Yes, I renamed my function and placed it on the then. This to have all my function calls in one place.
