### ISSUE TITLE
Format code to fix indentation and unnecessary empty lines

### ISSUE THREAD

**Issue by tnanhekhan** [heralt/web-app-from-scratch-1920#3]
https://github.com/heralt/web-app-from-scratch-1920/blob/2e143b71dbbd21d8f6c72e2314844beb20b8b383/assets/script.js#L17

https://github.com/heralt/web-app-from-scratch-1920/blob/2e143b71dbbd21d8f6c72e2314844beb20b8b383/assets/script.js#L32

https://github.com/heralt/web-app-from-scratch-1920/blob/2e143b71dbbd21d8f6c72e2314844beb20b8b383/assets/script.js#L38

(Use Ctrl + Alt +L in IntelliJ)

**Comment by heralt** [comment]
Yes, thanks for the feedback. will do.
