### ISSUE TITLE
Extraneous empty lines in head of the index.html

### ISSUE THREAD

**Issue by tnanhekhan** [heralt/web-app-from-scratch-1920#5]
https://github.com/heralt/web-app-from-scratch-1920/blob/2e143b71dbbd21d8f6c72e2314844beb20b8b383/index.html#L8

https://github.com/heralt/web-app-from-scratch-1920/blob/2e143b71dbbd21d8f6c72e2314844beb20b8b383/index.html#L10

**Comment by heralt** [comment]
Yes, I will remove these.
