### ISSUE TITLE
Consider using a forEach loop instaed of a for loop

### ISSUE THREAD

**Issue by joostf** [heralt/web-app-from-scratch-1920#9]
https://github.com/heralt/web-app-from-scratch-1920/blob/c7ad3329c434d0a2649948606bcd0030d5c7a2fd/assets/script.js#L42-L46

https://alligator.io/js/foreach-vs-for-loops/

**Comment by heralt** [comment]
Yes, ik heb de for-loop vervangen met een foreach-loop
